### ISSUE TITLE
Tutorial does not work if you change netcoreapp2.1 to netcoreapp3.1

### ISSUE THREAD

**Issue by AlbertoMonteiro** [AArnott/CodeGeneration.Roslyn#197] opened 2020-03-06 15:11 UTC
I've followed the tutorial on readme, then I changed the netcoreapp2.1 to netcoreapp3.1, the app ran, but the class TestPassed were not generated.

My Program.cs
```csharp
string runtime = System.Runtime.InteropServices.RuntimeInformation.FrameworkDescription;
System.Console.WriteLine(runtime);
foreach (var type in typeof(Program).Assembly.GetTypes())
    Console.WriteLine(type.FullName);
```
First run with `<TargetFramework>netcoreapp3.1</TargetFramework>`
Second run with `<TargetFramework>netcoreapp2.1</TargetFramework>`
![image](https://user-images.githubusercontent.com/836496/76095279-c7398e00-5fa2-11ea-8182-dec9ce733d3a.png)

If I change to netcoreapp3.0 the app does not even build

![image](https://user-images.githubusercontent.com/836496/76095541-344d2380-5fa3-11ea-8fcb-f72ca3efdc97.png)
Output
```
C:\Users\alberto_albuquerque\.nuget\packages\codegeneration.roslyn.buildtime\0.7.5-alpha\build\
CodeGeneration.Roslyn.BuildTime.targets(107,5): error MSB3073: 
O comando "dotnet codegen "@obj\Debug\netcoreapp3.0\Reflector.csproj.dotnet-codegen.rsp"" 
foi encerrado com o código 3. [C:\dev\codegentest\Reflector\Reflector.csproj]       

Ocorreu uma falha no build. Corrija os erros de build e execute novamente.
```
It is in portuguese(pt-br) but it says that the command dotnet codegen exited with code 3

**Comment by AlbertoMonteiro** [comment] 2020-03-06 15:17
I've changed the way to get the TF being used

```csharp
using System;
using System.Reflection;
using System.Runtime.Versioning;

namespace Reflector
{
    class Program
    {
        static void Main(string[] args)
        {
            var framework = Assembly
                .GetEntryAssembly()
                ?.GetCustomAttribute<TargetFrameworkAttribute>()?
                .FrameworkName;

            System.Console.WriteLine(framework);
            foreach (var type in typeof(Program).Assembly.GetTypes())
                Console.WriteLine(type.FullName);
        }
    }
}

```

![image](https://user-images.githubusercontent.com/836496/76096168-614e0600-5fa4-11ea-9c2d-052a74c07db5.png)

**Comment by AlbertoMonteiro** [comment] 2020-03-06 15:19
I've noticed that the filed was generated in 3.1, but with no class content, as you can see in the image below
![image](https://user-images.githubusercontent.com/836496/76096277-935f6800-5fa4-11ea-8d22-82ff5aa98ff8.png)

**Comment by amis92** [comment] 2020-03-31 11:23
I cannot reproduce using v0.7.43-alpha. Closing as deprecated.

In case you still experience problems @AlbertoMonteiro please reopen and provide a zip with the exact files you use.

**Closed by amis92** 2020-03-31 11:23 UTC
Labels: bug
