### ISSUE TITLE
Codegen seems a bit over zealous

### ISSUE THREAD

**Issue by mwpowellhtx** [AArnott/CodeGeneration.Roslyn#78] opened 2018-06-18 20:46 UTC
Is it me or does the Code Generation seem a bit over zealous? What do I mean by that. Correctly so, I observe that [code is being generated for my target scenario](/mwpowellhtx/Kingdom.Collections/blob/master/src/Kingdom.Collections.Enumerations.Generators.Tests/). However, I am also observing generated files, albeit empty, but for perhaps ``using`` statements, and that's it, that are also generated. Presumably, this is probably fairly benign in nature, but I just wanted to clarify that issue. This is how it should operate? Or is it potentially a problem with the generator itself?

**Comment by mwpowellhtx** [comment] 2018-06-18 20:51
In particular, see my [unit tests](/mwpowellhtx/Kingdom.Collections/blob/master/src/Kingdom.Collections.Enumerations.Generators.Tests/CardinalDirectionInSituFlagsEnumerationCodeGenerationTests.cs) for clarification; specifically the [in situational unit tests](/mwpowellhtx/Kingdom.Collections/blob/master/src/Kingdom.Collections.Enumerations.Generators.Tests/InSituFlagsEnumerationCodeGenerationTestsBase.cs). These are all passing, and I have also reviewed the generated output.

```C#
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

namespace Kingdom.Collections
{
    public partial class CardinalDirection
    {
        private CardinalDirection(byte[] bytes): base (bytes)
        {
        }

        public static CardinalDirection operator ~(CardinalDirection other) => other?.BitwiseNot();
        public static CardinalDirection operator &(CardinalDirection a, CardinalDirection b) => a?.BitwiseAnd(b);
        public static CardinalDirection operator |(CardinalDirection a, CardinalDirection b) => a?.BitwiseOr(b);
        public static CardinalDirection operator ^(CardinalDirection a, CardinalDirection b) => a?.BitwiseXor(b);
    }
}
```

**Comment by amis92** [comment] 2018-06-19 07:56
It's correct by current design. This issue is a duplicate of #33, in essence. It's an enhancement to be made. :)

**Comment by mwpowellhtx** [comment] 2018-06-19 14:24
@amis92 Is it in the pipeline, to your knowledge?

**Comment by AArnott** [comment] 2018-06-19 17:04
I absolutely appreciate PRs. But it's not quite true that I'm not actively developing. I'm just stuck. I haven't been able to get this to work on the latest VS 2017 for a while and I have a branch where I've made some changes but haven't got it all working. It's *really* hard to get roslyn, msbuild, VS and msbuild tasks to all work together to get a reliable code generation system working that also makes VS intellisense happy, works xplat on "dotnet build", etc.

I'm closing this as a dupe of #33

**Closed by AArnott** 2018-06-19 17:04 UTC

**Comment by mwpowellhtx** [comment] 2018-06-19 17:08
@AArnott No worries, thank you! As long as the issue is known and is (at least somewhat) on the radar, even though a workable solution is somewhat evasive.
