### ISSUE TITLE
Unable to build sample project in Visual Studio

### ISSUE THREAD

**Issue by Pzixel** [AArnott/CodeGeneration.Roslyn#26] opened 2017-06-02 14:15 UTC
I always get the same error:

```
6>------ Rebuild All started: Project: CodeGeneration.Roslyn.Tasks, Configuration: Debug Any CPU ------
6>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(4825,5): warning MSB3061: Unable to delete file "C:\Users\Alex\Source\Repos\CodeGeneration.Roslyn\bin\CodeGeneration.Roslyn.Tasks\Debug\net46\CodeGeneration.Roslyn.Tasks.dll". Access to the path 'C:\Users\Alex\Source\Repos\CodeGeneration.Roslyn\bin\CodeGeneration.Roslyn.Tasks\Debug\net46\CodeGeneration.Roslyn.Tasks.dll' is denied.
6>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(4148,5): warning MSB3026: Could not copy "C:\Users\Alex\Source\Repos\CodeGeneration.Roslyn\bin\CodeGeneration.Roslyn.Tasks.Helper\Debug\net46\CodeGeneration.Roslyn.Tasks.Helper.dll" to "C:\Users\Alex\Source\Repos\CodeGeneration.Roslyn\src\..\bin\CodeGeneration.Roslyn.Tasks\Debug\net46\CodeGeneration.Roslyn.Tasks.Helper.dll". Beginning retry 1 in 1000ms. The process cannot access the file 'C:\Users\Alex\Source\Repos\CodeGeneration.Roslyn\src\..\bin\CodeGeneration.Roslyn.Tasks\Debug\net46\CodeGeneration.Roslyn.Tasks.Helper.dll' because it is being used by another process.
6>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(4148,5): warning MSB3026: Could not copy "C:\Users\Alex\Source\Repos\CodeGeneration.Roslyn\bin\CodeGeneration.Roslyn.Tasks.Helper\Debug\net46\CodeGeneration.Roslyn.Tasks.Helper.dll" to "C:\Users\Alex\Source\Repos\CodeGeneration.Roslyn\src\..\bin\CodeGeneration.Roslyn.Tasks\Debug\net46\CodeGeneration.Roslyn.Tasks.Helper.dll". Beginning retry 2 in 1000ms. The process cannot access the file 'C:\Users\Alex\Source\Repos\CodeGeneration.Roslyn\src\..\bin\CodeGeneration.Roslyn.Tasks\Debug\net46\CodeGeneration.Roslyn.Tasks.Helper.dll' because it is being used by another process.
6>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(4148,5): warning MSB3026: Could not copy "C:\Users\Alex\Source\Repos\CodeGeneration.Roslyn\bin\CodeGeneration.Roslyn.Tasks.Helper\Debug\net46\CodeGeneration.Roslyn.Tasks.Helper.dll" to "C:\Users\Alex\Source\Repos\CodeGeneration.Roslyn\src\..\bin\CodeGeneration.Roslyn.Tasks\Debug\net46\CodeGeneration.Roslyn.Tasks.Helper.dll". Beginning retry 3 in 1000ms. The process cannot access the file 'C:\Users\Alex\Source\Repos\CodeGeneration.Roslyn\src\..\bin\CodeGeneration.Roslyn.Tasks\Debug\net46\CodeGeneration.Roslyn.Tasks.Helper.dll' because it is being used by another process.
6>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(4148,5): warning MSB3026: Could not copy "C:\Users\Alex\Source\Repos\CodeGeneration.Roslyn\bin\CodeGeneration.Roslyn.Tasks.Helper\Debug\net46\CodeGeneration.Roslyn.Tasks.Helper.dll" to "C:\Users\Alex\Source\Repos\CodeGeneration.Roslyn\src\..\bin\CodeGeneration.Roslyn.Tasks\Debug\net46\CodeGeneration.Roslyn.Tasks.Helper.dll". Beginning retry 4 in 1000ms. The process cannot access the file 'C:\Users\Alex\Source\Repos\CodeGeneration.Roslyn\src\..\bin\CodeGeneration.Roslyn.Tasks\Debug\net46\CodeGeneration.Roslyn.Tasks.Helper.dll' because it is being used by another process.
6>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(4148,5): warning MSB3026: Could not copy "C:\Users\Alex\Source\Repos\CodeGeneration.Roslyn\bin\CodeGeneration.Roslyn.Tasks.Helper\Debug\net46\CodeGeneration.Roslyn.Tasks.Helper.dll" to "C:\Users\Alex\Source\Repos\CodeGeneration.Roslyn\src\..\bin\CodeGeneration.Roslyn.Tasks\Debug\net46\CodeGeneration.Roslyn.Tasks.Helper.dll". Beginning retry 5 in 1000ms. The process cannot access the file 'C:\Users\Alex\Source\Repos\CodeGeneration.Roslyn\src\..\bin\CodeGeneration.Roslyn.Tasks\Debug\net46\CodeGeneration.Roslyn.Tasks.Helper.dll' because it is being used by another process.
6>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(4148,5): warning MSB3026: Could not copy "C:\Users\Alex\Source\Repos\CodeGeneration.Roslyn\bin\CodeGeneration.Roslyn.Tasks.Helper\Debug\net46\CodeGeneration.Roslyn.Tasks.Helper.dll" to "C:\Users\Alex\Source\Repos\CodeGeneration.Roslyn\src\..\bin\CodeGeneration.Roslyn.Tasks\Debug\net46\CodeGeneration.Roslyn.Tasks.Helper.dll". Beginning retry 6 in 1000ms. The process cannot access the file 'C:\Users\Alex\Source\Repos\CodeGeneration.Roslyn\src\..\bin\CodeGeneration.Roslyn.Tasks\Debug\net46\CodeGeneration.Roslyn.Tasks.Helper.dll' because it is being used by another process.
6>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(4148,5): warning MSB3026: Could not copy "C:\Users\Alex\Source\Repos\CodeGeneration.Roslyn\bin\CodeGeneration.Roslyn.Tasks.Helper\Debug\net46\CodeGeneration.Roslyn.Tasks.Helper.dll" to "C:\Users\Alex\Source\Repos\CodeGeneration.Roslyn\src\..\bin\CodeGeneration.Roslyn.Tasks\Debug\net46\CodeGeneration.Roslyn.Tasks.Helper.dll". Beginning retry 7 in 1000ms. The process cannot access the file 'C:\Users\Alex\Source\Repos\CodeGeneration.Roslyn\src\..\bin\CodeGeneration.Roslyn.Tasks\Debug\net46\CodeGeneration.Roslyn.Tasks.Helper.dll' because it is being used by another process.
6>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(4148,5): warning MSB3026: Could not copy "C:\Users\Alex\Source\Repos\CodeGeneration.Roslyn\bin\CodeGeneration.Roslyn.Tasks.Helper\Debug\net46\CodeGeneration.Roslyn.Tasks.Helper.dll" to "C:\Users\Alex\Source\Repos\CodeGeneration.Roslyn\src\..\bin\CodeGeneration.Roslyn.Tasks\Debug\net46\CodeGeneration.Roslyn.Tasks.Helper.dll". Beginning retry 8 in 1000ms. The process cannot access the file 'C:\Users\Alex\Source\Repos\CodeGeneration.Roslyn\src\..\bin\CodeGeneration.Roslyn.Tasks\Debug\net46\CodeGeneration.Roslyn.Tasks.Helper.dll' because it is being used by another process.
6>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(4148,5): warning MSB3026: Could not copy "C:\Users\Alex\Source\Repos\CodeGeneration.Roslyn\bin\CodeGeneration.Roslyn.Tasks.Helper\Debug\net46\CodeGeneration.Roslyn.Tasks.Helper.dll" to "C:\Users\Alex\Source\Repos\CodeGeneration.Roslyn\src\..\bin\CodeGeneration.Roslyn.Tasks\Debug\net46\CodeGeneration.Roslyn.Tasks.Helper.dll". Beginning retry 9 in 1000ms. The process cannot access the file 'C:\Users\Alex\Source\Repos\CodeGeneration.Roslyn\src\..\bin\CodeGeneration.Roslyn.Tasks\Debug\net46\CodeGeneration.Roslyn.Tasks.Helper.dll' because it is being used by another process.
6>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(4148,5): warning MSB3026: Could not copy "C:\Users\Alex\Source\Repos\CodeGeneration.Roslyn\bin\CodeGeneration.Roslyn.Tasks.Helper\Debug\net46\CodeGeneration.Roslyn.Tasks.Helper.dll" to "C:\Users\Alex\Source\Repos\CodeGeneration.Roslyn\src\..\bin\CodeGeneration.Roslyn.Tasks\Debug\net46\CodeGeneration.Roslyn.Tasks.Helper.dll". Beginning retry 10 in 1000ms. The process cannot access the file 'C:\Users\Alex\Source\Repos\CodeGeneration.Roslyn\src\..\bin\CodeGeneration.Roslyn.Tasks\Debug\net46\CodeGeneration.Roslyn.Tasks.Helper.dll' because it is being used by another process.
6>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(4148,5): error MSB3027: Could not copy "C:\Users\Alex\Source\Repos\CodeGeneration.Roslyn\bin\CodeGeneration.Roslyn.Tasks.Helper\Debug\net46\CodeGeneration.Roslyn.Tasks.Helper.dll" to "C:\Users\Alex\Source\Repos\CodeGeneration.Roslyn\src\..\bin\CodeGeneration.Roslyn.Tasks\Debug\net46\CodeGeneration.Roslyn.Tasks.Helper.dll". Exceeded retry count of 10. Failed.
6>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(4148,5): error MSB3021: Unable to copy file "C:\Users\Alex\Source\Repos\CodeGeneration.Roslyn\bin\CodeGeneration.Roslyn.Tasks.Helper\Debug\net46\CodeGeneration.Roslyn.Tasks.Helper.dll" to "C:\Users\Alex\Source\Repos\CodeGeneration.Roslyn\src\..\bin\CodeGeneration.Roslyn.Tasks\Debug\net46\CodeGeneration.Roslyn.Tasks.Helper.dll". The process cannot access the file 'C:\Users\Alex\Source\Repos\CodeGeneration.Roslyn\src\..\bin\CodeGeneration.Roslyn.Tasks\Debug\net46\CodeGeneration.Roslyn.Tasks.Helper.dll' because it is being used by another process.
6>Done building project "CodeGeneration.Roslyn.Tasks.csproj" -- FAILED.
```

I have just cloned repository, rebooted and only process running is VS so I don't know what's wrong with this I have even resintalled VS :) It didn't work. 

Probably it's because of uncommon place for binaries, but I have fresh VS installation and fresh repo so it should be something with repo itself, environment is fine.

**Comment by masaeedu** [comment] 2017-06-04 19:35
@Pzixel Are you applying the attribute in the same project where you have your code generator defined?

**Comment by Pzixel** [comment] 2017-06-05 09:15
@masaeedu I haven't this code changed at all. I just did `git clone & start vs & build solution`

**Comment by masaeedu** [comment] 2017-06-05 23:06
@Pzixel Is this a consistent issue across machines? Maybe try nuking your repo and trying again. I just tried the following and get a successful build:

```
git clone git@github.com:AArnott/CodeGeneration.Roslyn.git`
cd .\CodeGeneration.Roslyn\
dotnet restore
msbuild .\CodeGeneration.Roslyn.sln
```

**Comment by Pzixel** [comment] 2017-06-06 09:20
@masaeedu yes, it works (a little win here).

However, if you build solution through VS you get these errors:

![image](https://cloud.githubusercontent.com/assets/11201122/26822345/5f41941c-4ab2-11e7-89ac-54a92c088db0.png)

**Comment by masaeedu** [comment] 2017-06-06 17:56
@Pzixel The actual problem seems to be: ``The 'GenerateCodeFromAttributes' task failed unexpectedly. System.MethodMissingException: Method not found: '``...``ImmutableArray`1<SyntaxTree>'``. Did you restore your nuget packages?

**Comment by Pzixel** [comment] 2017-06-06 19:36
@masaeedu I ran it after building in console thus all packages have to be restored.

**Comment by Pzixel** [comment] 2017-06-13 10:47
No idea what's wrong here?

**Comment by orellabac** [comment] 2017-06-13 12:21
@Pzixel Isee from the screenshot that the console build was run as administrator. Are you running the VS as administrator too?

**Comment by Pzixel** [comment] 2017-06-13 12:25
@orellabac of course.

**Comment by orellabac** [comment] 2017-06-13 14:43
mmm I was able to reproduce your issue by using a similar path to what you are using. 
I do not know yet if the path has any influence. But I will be checking it.
![capture](https://user-images.githubusercontent.com/4247006/27088263-6af608ee-5014-11e7-864f-81dc8c55dec9.PNG)

**Comment by Pzixel** [comment] 2017-06-14 18:44
Bug is fixed in VS2017 update 2.

**Comment by Pzixel** [comment] 2017-06-16 22:42
Few days later I tried to build it again, and encountered this issue again. So it's not being fixed by update2. I can provide any additional information but I don't really know that's causing this issue.

**Comment by masaeedu** [comment] 2017-06-16 23:11
@pzixel Seems like a flaky issue. I don't know if you have a cloud storage account (onedrive/dropbox etc.), but if you could take a snapshot of a VM in which you've reproduced the issue we can experiment with it. I've personally been using the nuget packages in VS 2017 preview, and haven't had any issues. Even managed to implement XML type providers for C# 😄

**Comment by Pzixel** [comment] 2017-06-16 23:25
@masaeedu good idea. However, I'm not really sure if it's easy to share 30gb-minimum-image of VM where this issue is reproducable. However, I think it's a good idea to test on fresh VM, because it may be environment problem.

**Comment by Pzixel** [comment] 2017-06-17 09:14
Ok, I just installed the freshest W10 and VS and was able to repro this issue. I'm studying how can I share it (it's 50 GB)

**Comment by Pzixel** [comment] 2017-06-18 20:26
[Here is link](https://1drv.ms/u/s!Aho9_FLDH6NYg7ZpqlgqACAh1wqrUg) to my OneDrive folder. It's HyperV VM, 7gb archived, 20gb unzipped. Issue is totally reproducable there.

**Comment by Pzixel** [comment] 2017-06-21 08:12
Hey, what I found! If you open visual studio and try to compile form msbuild you get the same error! :)
![image](https://user-images.githubusercontent.com/11201122/27373858-7fda17be-5672-11e7-9871-179b22f7fe8a.png)

**Comment by Pzixel** [comment] 2018-09-11 09:17
This could be solved with killing all `msbuild` processes and starting **build** (not rebuild) again.

**Comment by Pzixel** [comment] 2018-09-11 09:18
So, There is a workaround, but issue is still here.

**Comment by amis92** [comment] 2018-09-11 10:02
File locks are no longer an issue since v0.4.74 by #83, I think?

**Comment by Pzixel** [comment] 2018-09-11 10:39
Hmm, interesting. Gonna check it later, thank you.

**Comment by AArnott** [comment] 2018-09-20 03:48
Ya, I thought #83 would have avoided this. Otherwise, what I tended to do was unload the project that couldn't build since it rarely needed to build during regular development in the sln anyway.

**Comment by amis92** [comment] 2019-01-22 20:52
I'll close this as it's possibly resolved, and I can't repro it with current master.

**Closed by amis92** 2019-01-22 20:52 UTC
