### ISSUE TITLE
Code generation not working in some projects

### ISSUE THREAD

**Issue by weltkante** [AArnott/CodeGeneration.Roslyn#8] opened 2016-09-08 18:09 UTC
After following the instructions on the front page I could get the dynamic code files generated, but they were not included in the project (i.e. compiler complains that generated methods don't exist) nor were they visible in intellisense.

After restarting VS (2015 Update 3) a few times at some point intellisense started to work and I could see the generated methods, however when compiling it still complains that the generated methods don't exist.

This is a WPF project; if I create a separate desktop-library project everything works, so I suspect WPF (or something contained in my project) is causing issues with the code generation. In the msbuild output I cannot see any difference between the WPF project and the library project (it just says the task starts and then completes). Any idea how to diagnose this further?

**Comment by Diagonactic** [comment] 2016-09-16 02:15
@weltkante I'm having the same problem, here.  Were you able to resolve it?

**Comment by weltkante** [comment] 2016-09-16 09:22
@Diagonactic nope, no idea what goes wrong, but I suspect its something with constructing a duplicate project for code generation. Maybe a WPF thing or maybe resolving referenced assemblies, no idea.

I might take another look at it over the weekend if I can figure out how to build and debug the code generation stuff.

**Comment by Diagonactic** [comment] 2016-09-16 17:22
@weltkante I was thinking the same thing when I was looking it over last night - or that the signature it's looking for in BuildTime is different than the one in CodeGeneration.

**Comment by weltkante** [comment] 2016-09-17 09:27
ok I tried debugging this but without success
* The source from github doesn't build cleanly with VS 2015 Update 3 (maybe this project is supposed to compile on "Dev15" ? no idea)
  * The nuproj files don't open even if I install the nuproj extension. I skipped these projects and fixed up the .targets file manually with hardcoded paths.
  * VS has issues resolving references. I resolved that by changing all projects to .NET 4.5 Profile 7 (not sure if that was required) and adding a reference to the 'Validation' nuget package which 'CodeGeneration.Roslyn' uses but does not reference (maybe its supposed to be pulled in automatically by the project-to-project reference, but that one doesn't seem to work properly, its got a yellow exclamation mark in the IDE)
* After building it and fixing up the .targets file with hardcoded paths and referencing it from my WPF project I get wierd errors from the code generator. It seems to mix up the paths of the main WPF project and the project containing my generator.

  I got that fixed by removing the project-to-project reference to the generator project and replacing it by a reference to the DLL of the generator.
* ... and then everything just works ...

Since the observed bug is not present in the code compiled for github, but instead a totally different bug happens, leaves me a bit helpless. Since I can't compile my own nuget packages (nuproj files don't work) I'll probably not be using the library for now, even though the idea by itself is cool and it would be great to get it working reliably.

I'll open separate issues for the problems observed when trying to build the project from github. I'll leave this issue open to track the problem with the current nuget package (0.1.57)

**Comment by Diagonactic** [comment] 2016-09-18 17:33
@weltkante I was able to get it to work after a bit of tinkering.

I'm not exactly sure what all I did, so this may be an incomplete set of instructions, but here's how I think I got the solution working.

I cloned "master", installed the nuget tools (turns out I didn't need them since the nuproj elements wouldn't load anyway -- VS 2015).  I updated the files to refer to Roslyn components versioned at 1.2.0.0 (I'm not sure if I did this in the project or if I did this in my own project; can't remember).  I built the CodeGenerator.Roslyn, CodeGenerator.Roslyn.Tasks and CodeGenerator.Roslyn.Attributes (portable in all cases).  I also changed the projects to build for .Net Framework 4.6 rather than 4.5.  Again, not sure what parts were actually necessary (or if any of it was) but it's working so I'm including everything I did.

Because the nuget project couldn't be created (I'm sure with a little work this could be sorted out), I moved the contents of the CodeGenerator.Roslyn and CodeGenerator.Roslyn.Tasks projects into the "tools" folder on the installed BuildTools reference in my solution.

This eliminated all of the errors on build and it created a .Generated.cs file (woohoo!), however, it was empty (D'oh!).  I think, though, that I have a problem with my code so I have to play with that for a bit.  But the errors are gone, at least.

One thing that stands out a little bit is that my entire solution was .Net Framework 4.6 based (it's an extension for Visual Studio 2015) so I, naturally, made my code generator a Framework 4.6 item.  This reminded me of an odd problem I had before where I had an interface defined in a Framework 4.5 project that used some built-in bits from 4.5, but implemented that interface in a class that was Framework 4.6 with the latest NuGet packages applied, and I'm fairly certain it was the Task type that was at fault back then.  I received the same error indicating that the method had no implementation in my other project.  

This was a year ago, though, so I'm not positive on that, either, but it may be that the return type of Task<T> is where the issue is here, too.  My CodeGeneration component was Framework 4.6.1 with the latest NuGet packages installed for each, so who knows?

Anyway, hope that helps!

**Comment by AArnott** [comment] 2017-03-11 23:48
With #15 this is now a VS2017 project. And hopefully is easier to build for everyone.

As for the failure in WPF, please let me know if it still repros with the 0.2.x release and we can reactivate.

**Comment by weltkante** [comment] 2017-03-12 10:43
Same error as before in WPF projects, the generated code is not passed to the compiler; using the 0.2.10 nuget package (via project.json) on a fresh VS 2017 professional installation and just copy/pasted the sample code on the repository front page.

**Comment by AArnott** [comment] 2017-03-12 15:13
Thanks for checking. I hadn't fixed anything specifically for WPF so this doesn't really surprise me.

**Comment by amis92** [comment] 2019-01-22 19:49
Closing as deprecated. Project went through major refactor, documentation was updated.

**Closed by amis92** 2019-01-22 19:49 UTC
